# Generated by Django 4.1.1 on 2022-09-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.ImageField(default='default_cover.jpg', upload_to='covers/'),
        ),
    ]
